from . import constants
from . import altitud_crew
from . import altitud_budget_line
from . import altitud_extra
from . import altitud_supply
from . import project_project
from . import project_task
from . import analytic_line
from . import hr_attendance
from . import hr_employee
from . import product_template
from . import sale_order
from . import purchase_order
from . import res_partner
from . import res_users
from . import res_company
